name: DistINR
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - torchaudio
  - pytorch-cuda=11.7
  - torchvision
  - pytorch
  - numba
  - netcdf4
  - matplotlib
  - h5py
  - pyevtk
  - vtk
