name: DistINR
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - blas=1.0
  - cuda=11.7.1
  - pip:
    - absl-py==1.3.0
    - cachetools==5.2.0
    - google-auth==2.14.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.50.0
    - gviz-api==1.10.0
    - importlib-metadata==5.0.0
    - markdown==3.4.1
    - markupsafe==2.1.1
    - oauthlib==3.2.2
    - pandas==1.5.1
    - pip==22.3.1
    - protobuf==3.19.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pytz==2022.6
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-profile==2.8.0
    - tensorboard-plugin-wit==1.8.1
    - torch-tb-profiler==0.4.0
    - torchaudio==0.13.0
    - torchvision==0.14.0
    - werkzeug==2.2.2
    - zipp==3.10.0
